name: Cypress Tests

on:
  pull_request:
    branches:
      - develop
      - staging
  workflow_dispatch:

jobs:
  cypress-run:
    permissions: write-all
    if: github.repository == 'ohcnetwork/care_fe'
    runs-on: ubuntu-latest
    env:
      REACT_CARE_API_URL: http://localhost:9000
      REACT_ENABLED_APPS: "ohcnetwork/care_hcx_fe@main"
      REACT_ENABLE_HCX: true
    steps:
      - name: Checkout 📥
        uses: actions/checkout@v3

      - name: Set backend branch
        id: backend-branch
        run: |
          if [[ '${{ github.event.pull_request.base.ref }}' == 'staging' ]]; then
            echo "branch=staging" >> $GITHUB_OUTPUT
          else
            echo "branch=develop" >> $GITHUB_OUTPUT
          fi

      - name: Checkout care 📥
        uses: actions/checkout@v3
        with:
          repository: ohcnetwork/care
          path: care
          ref: ${{ steps.backend-branch.outputs.branch }}

      - name: Start care docker containers 🐳
        run: |
          cd care
          echo DISABLE_RATELIMIT=True >> docker/.prebuilt.env
          echo "CORS_ALLOWED_ORIGINS=\"[\\\"http://localhost:4000\\\"]\"" >> docker/.prebuilt.env
          echo JWKS_BASE64=\"$(cat ../.github/runner-files/jwks.b64.txt)\" >> docker/.prebuilt.env
          make docker_config_file=docker-compose.pre-built.yaml up 
          make docker_config_file=docker-compose.pre-built.yaml load-dummy-data
          cd ..
        env:
          JWKS_BASE64: ${{ secrets.JWKS_BASE64 }}

      - name: Wait for care to be up ♻
        uses: nick-fields/retry@v2
        with:
          timeout_minutes: 1
          max_attempts: 5
          command: curl -o /dev/null -s -w "%{http_code}\n" http://localhost:9000
          on_retry_command: sleep 5
          
      - name: Determine PR Origin	
        id: pr_origin	
        run: echo "::set-output name=is_forked::$( echo ${{ github.event.pull_request.head.repo.fork }})"
      
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies 📦
        run: npm run install-all

      - name: Build ⚙️
        run: npm run build

      - name: Install Specific Chrome Version
        run: |
          sudo apt-get install -y wget
          sudo wget -q https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo apt-get install ./google-chrome-stable_current_amd64.deb

      - name: Fix Permissions for Test Files
        run: chmod -R +rwx cypress/e2e

      - name: Debug Test File Discovery
        run: find cypress/e2e -type f -name "*.cy.ts"

      - name: Run Cypress Tests in Parallel
        run: |
          npm run cy:parallel

      - name: Upload Cypress Artifacts 📸
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: cypress-artifacts
          path: cypress/{screenshots,videos}
